name: Zip Europa Universalis IV mod
description: >
  Creates a zip archive of the repository under a prefixed directory, alongside a descriptor file that can be extracted in the mod folder for easy use.
author: maxice8

branding:
  color: yellow
  icon: archive

inputs:
  mod-name:
    required: true
    description: >
      Name of the .mod descriptor file, .zip is prefixed to the end
  zip-name:
    required: false
    default: ''
    description: >
      Final name of the zip file.
      Defaults to the name of the mod if not present.
  prefix-name:
    required: false
    default: ''
    description: >
      Name of the prefix directory.
      Defaults to the name of the mod if not present.

outputs:
  zip-path:
    description: >
      Path to the created zip archive
    value: ${{ steps.zip.outputs.zip-path }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: zip
      id: zip
      env:
        MOD_NAME: ${{ inputs.mod-name }}
        ZIP_NAME: ${{ inputs.zip-name }}
        PREFIX_NAME: ${{ inputs.prefix-name }}

      run: ${{ github.action_path}}/mkzip.sh
      shell: bash
